swagger: "2.0"
info:
  description: "User service swagger"
  version: "1.0.0"
  title: "User service"
basePath: "/"
tags:
- name: "user"
  description: "Operations about user"
paths:
  /users/{user_id}:
    get:
      tags:
      - "user"
      summary: "Get user by user ID"
      description: ""
      operationId: "getUserByID"
      produces:
      - "application/json; charset=utf-8"
      parameters:
      - name: "user_id"
        in: "path"
        description: "The id that needs to be fetched. Use user1 for testing. "
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/User"
        400:
          description: "Invalid username supplied"
        404:
          description: "User not found"
definitions:
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      first_name:
        type: "string"
      last_name:
        type: "string"
   